name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC on Saturday
    - cron: "0 18 * * 6"
  workflow_dispatch:

permissions:
  contents: write # Cấp quyền ghi để có thể push ảnh vào repo

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Sử dụng token mặc định của GitHub
          USERNAME: taq0710 # Đã sửa thành username của bạn
      - name: Commit & Push
        run: |
          git config user.name taq0710
          git config user.email của_bạn@gmail.com # Thay email của bạn vào đây
          git add -A .
          git commit -m "generated"
          git push origin main
